server:
  port: 8080
spring:
  data:
    mongodb:
      database: task
      host: localhost
      port: 27017
  mvc:
    problemdetails:
      enabled: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /docs/swagger-ui.html